\ Z-machine string decoding tests.
\ Relies on having the Zork1.z3 and .z5 files handy for testing.
\ Should be run after main.fs, from the root of the project.

S" Zork1.z5" load-story restart \ v5 story loaded and ready, not running.

\ Reads and checks all the strings in Zork 1 (z5 edition).
\ Skips the ones with newlines.

T{ $12c98 zstr-decode   S" An old leather bag, bulging with coins, is here." str= -> true }T
T{ $12e50 zstr-decode   S" You have come to a dead end in the maze." str= -> true }T
T{ $12e68 zstr-decode   S" You have entered the Land of the Living Dead. Thousands of lost souls can be heard weeping and moaning. In the corner are stacked the remains of dozens of previous adventurers less fortunate than yourself. A passage exits to the north." str= -> true }T
T{ $12ef4 zstr-decode   S" You have entered a low cave with passages leading northwest and east." str= -> true }T
T{ $12f14 zstr-decode   S" You haven't a prayer of getting the coffin down there." str= -> true }T
T{ $12f34 zstr-decode   S" You have come to a dead end in the mine." str= -> true }T
T{ $12f4c zstr-decode   S"  has no effect." str= -> true }T
T{ $12f58 zstr-decode   S" You have two choices: 1. Leave  2. Become dinner." str= -> true }T
T{ $12f7c zstr-decode   S" Try the water, too." str= -> true }T
T{ $12f8c zstr-decode   S" Try throwing the knife or attacking someone with it." str= -> true }T
T{ $12fb0 zstr-decode   S" It requires the bell, book, and candles." str= -> true }T
T{ $12fc8 zstr-decode   S" Try them all. You should be able to find out." str= -> true }T
T{ $12fe8 zstr-decode   S" clockwork canary - 6 - 4 - in the egg" str= -> true }T
T{ $13004 zstr-decode   S" ... poured water on something burning?" str= -> true }T
T{ $1301c zstr-decode   S" over your head." str= -> true }T
T{ $13024 zstr-decode   S" Kill him with the sword." str= -> true }T
T{ $13034 zstr-decode   S" Use the buttons in the Maintenance Room." str= -> true }T
T{ $1304c zstr-decode   S" Use the gunk in the tube." str= -> true }T
T{ $1305c zstr-decode   S" By the way, have you ever taken a close look at the word ARAGAIN?" str= -> true }T
T{ $13088 zstr-decode   S" Use the garlic." str= -> true }T
T{ $13094 zstr-decode   S" sapphire bracelet - 5 - 5 - Gas Room" str= -> true }T
T{ $130b0 zstr-decode   S" Storm-tossed trees block your way." str= -> true }T
T{ $130c8 zstr-decode   S" Oh, no! You have walked into the slavering fangs of a lurking grue!" str= -> true }T
T{ $130f0 zstr-decode   S"  knocks out the " str= -> true }T
T{ $130f8 zstr-decode   S" Play ZORK II." str= -> true }T
T{ $13108 zstr-decode   S" I'm lost in the Forest." str= -> true }T
T{ $13118 zstr-decode   S" First, the first solution:" str= -> true }T
T{ $1312c zstr-decode   S" (Well, no one said they would work in a draft.) You can't carry a light source in. There is another way." str= -> true }T
T{ $13168 zstr-decode   S" ... read the matchbook?" str= -> true }T
T{ $13178 zstr-decode   S" At the end of the chain is a basket." str= -> true }T
T{ $13190 zstr-decode   S" On the ground is a red hot bell." str= -> true }T
T{ $131a4 zstr-decode   S" On the altar is a large black book, open to page 569." str= -> true }T
T{ $131c8 zstr-decode   S" On the table is an elongated brown sack, smelling of hot peppers." str= -> true }T
T{ $131f4 zstr-decode   S" On the shore lies Poseidon's own crystal trident." str= -> true }T
T{ $13218 zstr-decode   S" On the two ends of the altar are burning candles." str= -> true }T
T{ $13238 zstr-decode   S" On the ground is a pile of leaves." str= -> true }T
T{ $1324c zstr-decode   S" On the ground is a large platinum bar." str= -> true }T
T{ $13260 zstr-decode   S" At the end of the rainbow is a pot of gold." str= -> true }T
T{ $1327c zstr-decode   S"     " str= -> true }T
T{ $13280 zstr-decode   S" With great effort, you open the window far enough to allow entry." str= -> true }T
T{ $132ac zstr-decode   S"  parries." str= -> true }T
T{ $132b4 zstr-decode   S" It can be unlocked only from below." str= -> true }T
T{ $132c8 zstr-decode   S" Try winding it in the forest." str= -> true }T
T{ $132dc zstr-decode   S" It cannot be knocked down." str= -> true }T
T{ $132ec zstr-decode   S" It cannot be destroyed." str= -> true }T
T{ $132f8 zstr-decode   S" It cannot be opened." str= -> true }T
T{ $13304 zstr-decode   S" It can be used as a weapon, but isn't really necessary for anything." str= -> true }T
T{ $13330 zstr-decode   S" Touching the mirror in one transports you to the other." str= -> true }T
T{ $13354 zstr-decode   S" Yes." str= -> true }T
T{ $1336c zstr-decode   S" ... said WAIT or SCORE while dead (as a spirit)?" str= -> true }T
T{ $13398 zstr-decode   S" See the previous question." str= -> true }T
T{ $133ac zstr-decode   S" It doesn't oil the bolt well." str= -> true }T
T{ $133bc zstr-decode   S" U. N. E. S. N." str= -> true }T
T{ $133cc zstr-decode   S" Need a Drafty Room light source?" str= -> true }T
T{ $133e4 zstr-decode   S" See the alternative Cyclops answer." str= -> true }T
T{ $133f8 zstr-decode   S" Treasures: Their Values, Locations." str= -> true }T
T{ $13414 zstr-decode   S" ... tried swearing at ZORK I?" str= -> true }T
T{ $13430 zstr-decode   S" ... tried anything nasty with the bodies in Hades?" str= -> true }T
T{ $13450 zstr-decode   S" ... tried to take yourself (or the Thief, Troll or Cyclops)?" str= -> true }T
T{ $1347c zstr-decode   S" ... tried cutting things with the knife or sword?" str= -> true }T
T{ $1349c zstr-decode   S"  and devoured you!" str= -> true }T
T{ $134a8 zstr-decode   S" Too late for that." str= -> true }T
T{ $134b4 zstr-decode   S"  by an inch." str= -> true }T
T{ $134bc zstr-decode   S"  by a mile." str= -> true }T
T{ $134c4 zstr-decode   S"  and knocks it spinning." str= -> true }T
T{ $134d0 zstr-decode   S" You must unlock it." str= -> true }T
T{ $134dc zstr-decode   S" You must open the egg first." str= -> true }T
T{ $134f0 zstr-decode   S" Still, how do I get through the Maze?" str= -> true }T
T{ $13508 zstr-decode   S" You must exorcise the evil spirits." str= -> true }T
T{ $13520 zstr-decode   S" You must activate the panel. (Green bubble lights up)." str= -> true }T
T{ $13544 zstr-decode   S" Diamonds are pure carbon in a crystalline form. They are created under tremendous heat and pressure." str= -> true }T
T{ $13584 zstr-decode   S" You may appear in the forest with your belongings scattered (valuables below ground, nonvaluables above)." str= -> true }T
T{ $135c8 zstr-decode   S" You may wander as a spirit until you find a way to resurrect yourself." str= -> true }T
T{ $135f4 zstr-decode   S" How Points are Scored." str= -> true }T
T{ $13604 zstr-decode   S" An ornamented sceptre, tapering to a sharp point, is here." str= -> true }T
T{ $13940 zstr-decode   S" That was just a bit too far down." str= -> true }T
T{ $13958 zstr-decode   S" The axe sweeps past as you jump aside." str= -> true }T
T{ $13970 zstr-decode   S" The axe crashes against the rock, throwing sparks!" str= -> true }T
T{ $13990 zstr-decode   S" The axe gets you right in the side. Ouch!" str= -> true }T
T{ $139a8 zstr-decode   S" An axe stroke makes a deep wound in your leg." str= -> true }T
T{ $139c8 zstr-decode   S" The axe hits your " str= -> true }T
T{ $139d4 zstr-decode   S" The axe knocks your " str= -> true }T
T{ $139dc zstr-decode   S" Q = main menu" str= -> true }T
T{ $139e8 zstr-decode   S" They can be taken, counted, or burned." str= -> true }T
T{ $13a04 zstr-decode   S" You need the skeleton key." str= -> true }T
T{ $13a14 zstr-decode   S" The artist was sloppy." str= -> true }T
T{ $13a24 zstr-decode   S" For a hint, turn the page in the black book." str= -> true }T
T{ $13a40 zstr-decode   S" The altar has magical powers." str= -> true }T
T{ $13a54 zstr-decode   S" You need the wrench." str= -> true }T
T{ $13a60 zstr-decode   S" You need the air pump, which is north of the Reservoir." str= -> true }T
T{ $13a7c zstr-decode   S" Matches." str= -> true }T
T{ $13a84 zstr-decode   S" Objects, including light sources, can be placed in the basket. The basket can be lowered and raised." str= -> true }T
T{ $13ac0 zstr-decode   S" Objects seem to move or disappear." str= -> true }T
T{ $13ad8 zstr-decode   S" A hot pepper sandwich is here." str= -> true }T
T{ $13aec zstr-decode   S" The " str= -> true }T
T{ $13af0 zstr-decode   S" The blow lands, making a shallow gash in the " str= -> true }T
T{ $13b0c zstr-decode   S" The butt of his stiletto cracks you on the skull, and you stagger back." str= -> true }T
T{ $13b34 zstr-decode   S" No one can fix it. Really!" str= -> true }T
T{ $13b48 zstr-decode   S" Are the leaves useful for anything?" str= -> true }T
T{ $13b60 zstr-decode   S" Wait until the reservoir is empty, then close the gates." str= -> true }T
T{ $13b84 zstr-decode   S" You'll never reach the rope." str= -> true }T
T{ $13b98 zstr-decode   S" Brushing your teeth with it is not sensible." str= -> true }T
T{ $13bb0 zstr-decode   S" You'll know when the time comes." str= -> true }T
T{ $13bc8 zstr-decode   S" The blue button causes a water pipe to burst." str= -> true }T
T{ $13be4 zstr-decode   S" The brown bubble deactivates the control panel." str= -> true }T
T{ $13c04 zstr-decode   S" Evidently the ancient Zorkers did not have strong truth-in-advertising laws. Take nothing for granite." str= -> true }T
T{ $13c44 zstr-decode   S" Why does the sword glow?" str= -> true }T
T{ $13c54 zstr-decode   S" General Questions" str= -> true }T
T{ $13c64 zstr-decode   S" ... waved the sceptre while standing on the rainbow?" str= -> true }T
T{ $13c88 zstr-decode   S" This is a forest, with trees in all directions. To the east, there appears to be sunlight." str= -> true }T
T{ $13cb8 zstr-decode   S" This is a dimly lit forest, with large trees all around." str= -> true }T
T{ $13cd8 zstr-decode   S" This is a path winding through a dimly lit forest. The path heads north-south here. One particularly large tree with some low branches stands at the edge of the path." str= -> true }T
T{ $13d30 zstr-decode   S" This is the attic. The only exit is a stairway leading down." str= -> true }T
T{ $13d50 zstr-decode   S" This is a small room with passages to the east and south and a forbidding hole leading west. Bloodstains and deep scratches (perhaps made by an axe) mar the walls." str= -> true }T
T{ $13da4 zstr-decode   S" The chasm probably leads straight to the infernal regions." str= -> true }T
T{ $13dc4 zstr-decode   S" This is an art gallery. Most of the paintings have been stolen by vandals with exceptional taste. The vandals left through either the north or west exits." str= -> true }T
T{ $13e18 zstr-decode   S" This appears to have been an artist's studio. The walls and floors are splattered with paints of 69 different colors. Strangely enough, nothing of value is hanging here. At the south end of the room is an open door (also covered with paint). A dark and narrow chimney leads up from a fireplace; although you might be able to get up it, it seems unlikely you could get back down." str= -> true }T
T{ $13eec zstr-decode   S" This is part of a maze of twisty little passages, all alike." str= -> true }T
T{ $13f14 zstr-decode   S" This is part of a maze of twisty little passages, all alike. A skeleton, probably the remains of a luckless adventurer, lies here." str= -> true }T
T{ $13f60 zstr-decode   S" The cyclops doesn't look like he'll let you past." str= -> true }T
T{ $13f78 zstr-decode   S" This is a long passage. To the west is one entrance. On the east there is an old wooden door, with a large opening in it (about cyclops sized)." str= -> true }T
T{ $13fc0 zstr-decode   S" This is a large room, whose east wall is solid granite. A number of discarded bags, which crumble at your touch, are scattered about on the floor. There is an exit down a staircase." str= -> true }T
T{ $14020 zstr-decode   S" The channel is too narrow." str= -> true }T
T{ $14030 zstr-decode   S" This is a tiny cave with entrances west and north, and a staircase leading down." str= -> true }T
T{ $14054 zstr-decode   S" This is a tiny cave with entrances west and north, and a dark, forbidding staircase leading down." str= -> true }T
T{ $14084 zstr-decode   S" This is a cold and damp corridor where a long east-west passageway turns into a southward path." str= -> true }T
T{ $140bc zstr-decode   S" This is a long and narrow corridor where a long north-south passageway briefly narrows even further." str= -> true }T
T{ $140f4 zstr-decode   S" This is a winding passage. It seems that there are only exits on the east and north." str= -> true }T
T{ $1411c zstr-decode   S" This is an ancient room, long under water. There is an exit to the south and a staircase leading up." str= -> true }T
T{ $14148 zstr-decode   S" This is a narrow east-west passageway. There is a narrow stairway leading down at the north end of the room." str= -> true }T
T{ $14178 zstr-decode   S" This is a circular stone room with passages in all directions. Several of them have unfortunately been blocked by cave-ins." str= -> true }T
T{ $141c0 zstr-decode   S" This cave has exits to the west and east, and narrows to a crack toward the south. The earth is particularly damp here." str= -> true }T
T{ $14204 zstr-decode   S" This is a high north-south passage, which forks to the northeast." str= -> true }T
T{ $14228 zstr-decode   S" This is a room which looks like an Egyptian tomb. There is an ascending staircase to the west." str= -> true }T
T{ $14254 zstr-decode   S" This is the north end of a large temple. On the east wall is an ancient inscription, probably a prayer in a long-forgotten language. Below the prayer is a staircase leading down. The west wall is solid granite. The exit to the north end of the room is through huge marble pillars." str= -> true }T
T{ $142dc zstr-decode   S" This is the south end of a large temple. In front of you is what appears to be an altar. In one corner is a small hole in the floor which leads into darkness. You probably could not get back up it." str= -> true }T
T{ $1439c zstr-decode   S" This is what appears to have been the maintenance room for Flood Control Dam #3. Apparently, this room has been ransacked recently, for most of the valuable equipment is gone. On the wall in front of you is a group of buttons colored blue, yellow, brown, and red. There are doorways to the west and south." str= -> true }T
T{ $14444 zstr-decode   S" This is a sand-filled cave whose exit is to the southwest." str= -> true }T
T{ $14468 zstr-decode   S" This is a large room, in the middle of which is a small shaft descending through the floor into darkness below. To the west and the north are exits from this room. Constructed over the top of the shaft is a metal framework to which a heavy iron chain is attached." str= -> true }T
T{ $144e8 zstr-decode   S" This is a small nondescript room. However, from the direction of a small descending staircase a foul odor can be detected. To the south is a narrow tunnel." str= -> true }T
T{ $14534 zstr-decode   S" This is a small room which smells strongly of coal gas. There is a short climb up some stairs and a narrow tunnel leading east." str= -> true }T
T{ $14574 zstr-decode   S" This is a very small room. In the corner is a rickety wooden ladder, leading downward. It might be safe to descend. There is also a staircase leading upward." str= -> true }T
T{ $145c4 zstr-decode   S" This is a rather wide room. On one side is the bottom of a narrow wooden ladder. To the west and the south are passages leaving the room." str= -> true }T
T{ $14608 zstr-decode   S" This is a long and narrow passage, which is cluttered with broken timbers. A wide passage comes from the east and turns at the west end of the room into a very narrow passageway. From the west comes a strong draft." str= -> true }T
T{ $14674 zstr-decode   S" This is a small drafty room in which is the bottom of a long shaft. To the south is a passageway and to the east a very narrow passage. In the shaft can be seen a heavy iron chain." str= -> true }T
T{ $146d0 zstr-decode   S" This is a nondescript part of a coal mine." str= -> true }T
T{ $1477c zstr-decode   S" Wheeeeeeeeee!!!!!" str= -> true }T
T{ $1478c zstr-decode   S" What a concept!" str= -> true }T
T{ $14804 zstr-decode   S" The cyclops seems somewhat agitated." str= -> true }T
T{ $14818 zstr-decode   S" The cyclops appears to be getting more agitated." str= -> true }T
T{ $14830 zstr-decode   S" The cyclops is moving about the room, looking for something." str= -> true }T
T{ $14848 zstr-decode   S" The cyclops was looking for salt and pepper. No doubt they are condiments for his upcoming snack." str= -> true }T
T{ $1487c zstr-decode   S" The cyclops is moving toward you in an unfriendly manner." str= -> true }T
T{ $1489c zstr-decode   S" The candles grow shorter." str= -> true }T
T{ $148a8 zstr-decode   S" The candles are becoming quite short." str= -> true }T
T{ $148bc zstr-decode   S" The candles won't last long now." str= -> true }T
T{ $148cc zstr-decode   S"  square in the heart: He dies." str= -> true }T
T{ $148e0 zstr-decode   S" You parry a lightning thrust, and the thief salutes you with a grim nod." str= -> true }T
T{ $14908 zstr-decode   S" You parry a low thrust, and your " str= -> true }T
T{ $1491c zstr-decode   S" What a concept! You need a psychiatrist." str= -> true }T
T{ $14938 zstr-decode   S" This is not China." str= -> true }T
T{ $14944 zstr-decode   S" This is a actually a dummy question. Do not use the presence or absence of a question on a certain topic as an indication of what is important." str= -> true }T
T{ $1499c zstr-decode   S" What is a grue?" str= -> true }T
T{ $149a8 zstr-decode   S" What do I do with the axe?" str= -> true }T
T{ $149b8 zstr-decode   S" This space intentionally left blank." str= -> true }T
T{ $149d0 zstr-decode   S" What do I do with the rusty knife?" str= -> true }T
T{ $149e8 zstr-decode   S" What do I do with the skeleton?" str= -> true }T
T{ $149fc zstr-decode   S" What happens if you hang around too long, or give something to the Cyclops?" str= -> true }T
T{ $14a2c zstr-decode   S" What is causing the loud roar?" str= -> true }T
T{ $14a40 zstr-decode   S" This solution to the Loud Room requires no object or information from elsewhere in the game." str= -> true }T
T{ $14a74 zstr-decode   S" What happens when you type something ... something ... something?" str= -> true }T
T{ $14aa4 zstr-decode   S" What is usually done at altars?" str= -> true }T
T{ $14abc zstr-decode   S" What is the green bubble for?" str= -> true }T
T{ $14ad0 zstr-decode   S" What do I do with the tube?" str= -> true }T
T{ $14ae0 zstr-decode   S" What is the screwdriver for?" str= -> true }T
T{ $14af0 zstr-decode   S" What about Maintenance Room buttons?" str= -> true }T
T{ $14b08 zstr-decode   S" What is the pile of plastic good for?" str= -> true }T
T{ $14b20 zstr-decode   S" What is the valve for?" str= -> true }T
T{ $14b30 zstr-decode   S" What will placate the River God?" str= -> true }T
T{ $14b48 zstr-decode   S" What have you tried to throw into the river?" str= -> true }T
T{ $14b60 zstr-decode   S" What do I do about the bat?" str= -> true }T
T{ $14b70 zstr-decode   S" What is the timber for?" str= -> true }T
T{ $14b80 zstr-decode   S" What do I do about the Thief?" str= -> true }T
T{ $14b94 zstr-decode   S" The chimney will allow you to carry one object at a time in addition to your lamp." str= -> true }T
T{ $14bc4 zstr-decode   S" What do the engravings mean?" str= -> true }T
T{ $14bd8 zstr-decode   S" What makes you think you can?" str= -> true }T
T{ $14be8 zstr-decode   S" What happens when you die?" str= -> true }T
T{ $14bfc zstr-decode   S" What do I do with the stiletto?" str= -> true }T
T{ $14c10 zstr-decode   S" What are you talking about?" str= -> true }T
T{ $14c24 zstr-decode   S" This is not necessary to complete the game." str= -> true }T
T{ $14c3c zstr-decode   S" The deceased adventurer's useless lantern is here." str= -> true }T
T{ $14e1c zstr-decode   S" The door is boarded and you can't remove the boards." str= -> true }T
T{ $14e38 zstr-decode   S" The door is nailed shut." str= -> true }T
T{ $14e48 zstr-decode   S" The dam blocks your way." str= -> true }T
T{ $14e58 zstr-decode   S" A valiant attempt." str= -> true }T
T{ $14e68 zstr-decode   S" The door reluctantly opens to reveal a rickety staircase descending into darkness." str= -> true }T
T{ $14e94 zstr-decode   S" The door swings shut and closes." str= -> true }T
T{ $14ea8 zstr-decode   S"  away." str= -> true }T
T{ $14eb0 zstr-decode   S" Of what use is the canary?" str= -> true }T
T{ $14ec4 zstr-decode   S" The description of one of the treasures, and the result of manipulating it properly were meant to be subtle hints." str= -> true }T
T{ $14f08 zstr-decode   S" A valiant attempt, but this is getting you nowhere." str= -> true }T
T{ $14f24 zstr-decode   S" (Use only as a last resort.)" str= -> true }T
T{ $14f68 zstr-decode   S" The engravings were incised in the living rock of the cave wall by an unknown hand. They depict, in symbolic form, the beliefs of the ancient Zorkers. Skillfully interwoven with the bas reliefs are excerpts illustrating the major religious tenets of that time. Unfortunately, a later age seems to have considered them blasphemous and just as skillfully excised them." str= -> true }T
T{ $1503c zstr-decode   S" The east wall is solid rock." str= -> true }T
T{ $1504c zstr-decode   S" 's weapon is knocked to the floor, leaving him unarmed." str= -> true }T
T{ $15070 zstr-decode   S" jewels" str= -> true }T
T{ $15074 zstr-decode   S" Someone else in the game can do it." str= -> true }T
T{ $1508c zstr-decode   S" Someone from Infocom would love to hear how you did it." str= -> true }T
T{ $150ac zstr-decode   S" The entrance is in the house." str= -> true }T
T{ $150bc zstr-decode   S" When you have all 350 points, you'll be able to enter the Barrow." str= -> true }T
T{ $150e8 zstr-decode   S" jewel-encrusted egg - 5 - 5 - in nest in tree" str= -> true }T
T{ $1510c zstr-decode   S" jeweled scarab - 5 - 5 - buried in Sandy Cave" str= -> true }T
T{ $15130 zstr-decode   S" pot of gold - 10 - 10 - End of Rainbow" str= -> true }T
T{ $15150 zstr-decode   S" The forest becomes impenetrable to the north." str= -> true }T
T{ $1516c zstr-decode   S" The forest thins out, revealing impassable mountains." str= -> true }T
T{ $15190 zstr-decode   S" You should have looked before you leaped." str= -> true }T
T{ $151a4 zstr-decode   S" Goodbye." str= -> true }T
T{ $151ac zstr-decode   S" You splash around for a while, fighting the current, then you drown." str= -> true }T
T{ $151d8 zstr-decode   S" You seem to be digging a hole here." str= -> true }T
T{ $151ec zstr-decode   S" The fatal blow strikes the " str= -> true }T
T{ $151fc zstr-decode   S" The force of your blow knocks the " str= -> true }T
T{ $1520c zstr-decode   S" The flat of the troll's axe hits you delicately on the head, knocking you out for a brief moment." str= -> true }T
T{ $15240 zstr-decode   S" The flat of the troll's axe skins across your forearm." str= -> true }T
T{ $1525c zstr-decode   S" You stagger back under a hail of axe strokes." str= -> true }T
T{ $1527c zstr-decode   S" Trapdoors can be hidden." str= -> true }T
T{ $1528c zstr-decode   S" For fun, try saying ODYSSEUS elsewhere." str= -> true }T
T{ $152ac zstr-decode   S" Not without a boat." str= -> true }T
T{ $152bc zstr-decode   S" ZORK I is as fair as baseball. Three strikes and you're out." str= -> true }T
T{ $152e8 zstr-decode   S" You try to ascend the ramp, but it is impossible, and you slide back down." str= -> true }T
T{ $15314 zstr-decode   S" The grating is closed." str= -> true }T
T{ $1531c zstr-decode   S" Are you out of your mind?" str= -> true }T
T{ $1532c zstr-decode   S" Are you enjoying yourself?" str= -> true }T
T{ $15340 zstr-decode   S"  hits you squarely in the head. Normally, this wouldn't do much damage, but by incredible mischance, you fall over backwards trying to duck, and break your neck, justice being swift and merciful in the Great Underground Empire." str= -> true }T
T{ $153c8 zstr-decode   S" The grating opens." str= -> true }T
T{ $153d0 zstr-decode   S" The grating opens to reveal trees above you." str= -> true }T
T{ $153e8 zstr-decode   S" A furious exchange, and the " str= -> true }T
T{ $153f8 zstr-decode   S" Q = see hint menu" str= -> true }T
T{ $15408 zstr-decode   S" Is the nest useful for anything?" str= -> true }T
T{ $1541c zstr-decode   S" The grating and key can be found in the Maze." str= -> true }T
T{ $15434 zstr-decode   S" Is there a way to make it less slippery?" str= -> true }T
T{ $1544c zstr-decode   S" Let the dead rest in peace." str= -> true }T
T{ $15460 zstr-decode   S" Is there a way to control the flow of water?" str= -> true }T
T{ $1547c zstr-decode   S" Is the rainbow significant?" str= -> true }T
T{ $15490 zstr-decode   S" Is the basket on the chain useful?" str= -> true }T
T{ $154a4 zstr-decode   S" Is the coal good for anything?" str= -> true }T
T{ $154b8 zstr-decode   S" Is the gas of any use?" str= -> true }T
T{ $154c8 zstr-decode   S" Elvish swords are magical, and glow with a blue light when dangers (particularly dangerous beings) are near." str= -> true }T
T{ $15510 zstr-decode   S" Are you sure you want to know?" str= -> true }T
T{ $15524 zstr-decode   S" These points plus all the treasure points make 350. When you have all 350 points, the twentieth treasure will appear in the case -- a map which leads (indirectly) to 400 more points (ZORK II)." str= -> true }T
T{ $155ac zstr-decode   S" crystal trident - 4 - 11 - Atlantis Room" str= -> true }T
T{ $155cc zstr-decode   S" jade figurine - 5 - 5 - Bat Room" str= -> true }T
T{ $155e4 zstr-decode   S" crystal skull - 10 - 10 - Land of Living Dead" str= -> true }T
T{ $15608 zstr-decode   S" brass bauble - 1 - 1 - the songbird has it" str= -> true }T
T{ $15628 zstr-decode   S" The hole collapses, smothering you." str= -> true }T
T{ $15640 zstr-decode   S" The hole is getting deeper, but that's about it." str= -> true }T
T{ $1565c zstr-decode   S" The haft of your " str= -> true }T
T{ $15664 zstr-decode   S"  removes his head." str= -> true }T
T{ $15670 zstr-decode   S"  on the wrist, but it's not serious." str= -> true }T
T{ $15688 zstr-decode   S" Slash! Your blow lands! That one hit an artery, it could be serious!" str= -> true }T
T{ $156b4 zstr-decode   S" Slash! Your stroke connects! This could be serious!" str= -> true }T
T{ $156d4 zstr-decode   S" They're great for hiding gratings." str= -> true }T
T{ $156ec zstr-decode   S" Isn't there some sort of glop you could apply?" str= -> true }T
T{ $15708 zstr-decode   S" I popped the boat!" str= -> true }T
T{ $15714 zstr-decode   S" Look around." str= -> true }T
T{ $15744 zstr-decode   S"  arm." str= -> true }T
T{ $15748 zstr-decode   S" It makes the room more interesting and the adventurer more confused." str= -> true }T
T{ $15788 zstr-decode   S" Who is the lean and hungry gentleman?" str= -> true }T
T{ $157a0 zstr-decode   S" Fortunately, there is still one chance for you to be a vandal, for on the far wall is a painting of unparalleled beauty." str= -> true }T
T{ $157e0 zstr-decode   S" Beside the skeleton is a rusty knife." str= -> true }T
T{ $157f8 zstr-decode   S" Beside you on the branch is a small bird's nest." str= -> true }T
T{ $15814 zstr-decode   S" You would need a machete to go further west." str= -> true }T
T{ $15830 zstr-decode   S" You would drown." str= -> true }T
T{ $15838 zstr-decode   S" You wouldn't fit and would die if you could." str= -> true }T
T{ $15850 zstr-decode   S" Pushing the " str= -> true }T
T{ $15858 zstr-decode   S" coins" str= -> true }T
T{ $1585c zstr-decode   S" Something is attracted to its singing." str= -> true }T
T{ $15878 zstr-decode   S" You won't get past the Troll while he is conscious." str= -> true }T
T{ $15898 zstr-decode   S" What's the studio paint all about?" str= -> true }T
T{ $158b0 zstr-decode   S" What's the best coal mine route?" str= -> true }T
T{ $158c8 zstr-decode   S" What's the Granite Wall about?" str= -> true }T
T{ $158e0 zstr-decode   S" What's with the granite walls?" str= -> true }T
T{ $158f4 zstr-decode   S" What's the best image-caster?" str= -> true }T
T{ $1590c zstr-decode   S"  is battered into unconsciousness." str= -> true }T
T{ $15924 zstr-decode   S" Why might the room be drafty?" str= -> true }T
T{ $15938 zstr-decode   S" The knowledgeable critic, I.Q. Roundhead, wrote a ten-volume study of the engravings of the ancient Zorkers. To make a long story short, he concluded that the Zorkers were very strange people." str= -> true }T
T{ $159b8 zstr-decode   S" A large coil of rope is lying in the corner." str= -> true }T
T{ $159d0 zstr-decode   S" Just in time you steer away from the rocks." str= -> true }T
T{ $159ec zstr-decode   S" A troll is here." str= -> true }T
T{ $159f4 zstr-decode   S" The leaves burn, and so do you." str= -> true }T
T{ $15a08 zstr-decode   S" The lamp appears a bit dimmer." str= -> true }T
T{ $15a18 zstr-decode   S" The lamp is definitely dimmer now." str= -> true }T
T{ $15a30 zstr-decode   S" The lamp is nearly out." str= -> true }T
T{ $15a40 zstr-decode   S"  is confused and can't fight back." str= -> true }T
T{ $15a54 zstr-decode   S" It takes a great deal of manual dexterity and the proper tools." str= -> true }T
T{ $15a7c zstr-decode   S" Ring the bell, light the candles, and read the black book." str= -> true }T
T{ $15aa0 zstr-decode   S" Just stay in the boat and wait." str= -> true }T
T{ $15ab4 zstr-decode   S" The location is the altar in the South Temple." str= -> true }T
T{ $15ad0 zstr-decode   S" bag of coins - 10 - 5 - in the Maze" str= -> true }T
T{ $15b64 zstr-decode   S" The mountains are impassable." str= -> true }T
T{ $15b78 zstr-decode   S" An unconscious troll is sprawled on the floor. All passages out of the room are open." str= -> true }T
T{ $15ba4 zstr-decode   S"  is disarmed by a subtle feint past his guard." str= -> true }T
T{ $15bc4 zstr-decode   S" The monster smashes his huge fist into your chest, breaking several ribs." str= -> true }T
T{ $15bf0 zstr-decode   S" The monster grabs you on the wrist, squeezes, and you drop your " str= -> true }T
T{ $15c14 zstr-decode   S" Absolutely certain?" str= -> true }T
T{ $15c24 zstr-decode   S" (The treasure will be listed, followed by the points for taking it, the points for putting it in the trophy case, then the place it is found.)" str= -> true }T
T{ $15c78 zstr-decode   S"  into dreamland." str= -> true }T
T{ $15c84 zstr-decode   S" Finishing you off, the thief inserts his blade into your heart." str= -> true }T
T{ $15ca8 zstr-decode   S" A long, theatrical slash. You catch it on your " str= -> true }T
T{ $15cc4 zstr-decode   S"  RETURN = see hint" str= -> true }T
T{ $15cd8 zstr-decode   S" Did you ever try touching or rubbing it?" str= -> true }T
T{ $15cf4 zstr-decode   S" Yes, but not with your finger." str= -> true }T
T{ $15d04 zstr-decode   S" Did you try blowing into it?" str= -> true }T
T{ $15d18 zstr-decode   S" Pointy objects can puncture a plastic boat. You should not carry them on. Put them in the boat before boarding or put them into a container, such as the brown sack, first." str= -> true }T
T{ $15d80 zstr-decode   S" Did you try dropping everything?" str= -> true }T
T{ $15d98 zstr-decode   S" Did you ever wonder where the shaft with the basket led?" str= -> true }T
T{ $15db8 zstr-decode   S" The nasty knife is a marginally more effective weapon to use against him." str= -> true }T
T{ $15de8 zstr-decode   S" beautiful painting - 4 - 6 - Gallery" str= -> true }T
T{ $15e04 zstr-decode   S"  RETURN = See hint" str= -> true }T
T{ $15e18 zstr-decode   S" From the chain is suspended a basket." str= -> true }T
T{ $15ee8 zstr-decode   S" Only Santa Claus climbs down chimneys." str= -> true }T
T{ $15f04 zstr-decode   S" It's a long way..." str= -> true }T
T{ $15f10 zstr-decode   S" Well, you seem to have been brushing your teeth with some sort of glue. As a result, your mouth gets glued together (with your nose) and you die of respiratory failure." str= -> true }T
T{ $15f74 zstr-decode   S" Well, you really did it that time. Is suicide painless?" str= -> true }T
T{ $15f98 zstr-decode   S" It's curtains for the " str= -> true }T
T{ $15fa4 zstr-decode   S"  out of your hand. It falls to the floor." str= -> true }T
T{ $15fbc zstr-decode   S"  out of your hands, and it drops to the floor." str= -> true }T
T{ $15fd4 zstr-decode   S" INVISICLUES (tm)" str= -> true }T
T{ $15fe8 zstr-decode   S" Only the Thief can open the egg. Give it to him or leave it underground where he will find it." str= -> true }T
T{ $16048 zstr-decode   S" From the Troll Room to the Grating Room:" str= -> true }T
T{ $16060 zstr-decode   S" From the Grating Room to the Troll Room:" str= -> true }T
T{ $16078 zstr-decode   S" From the Troll Room to the Cyclops Room:" str= -> true }T
T{ $1608c zstr-decode   S" From the Cyclops Room to the Troll Room:" str= -> true }T
T{ $160a0 zstr-decode   S" From the Grating Room to the Cyclops Room:" str= -> true }T
T{ $160b4 zstr-decode   S" From the Cyclops Room to the Grating Room:" str= -> true }T
T{ $160c8 zstr-decode   S" The order in which you perform the ceremony is very important." str= -> true }T
T{ $160ec zstr-decode   S" Read the tube." str= -> true }T
T{ $160f8 zstr-decode   S" Read the label." str= -> true }T
T{ $16104 zstr-decode   S" Well, what did you expect?" str= -> true }T
T{ $16118 zstr-decode   S" It's a vampire bat." str= -> true }T
T{ $16124 zstr-decode   S" From the Gas Room to Ladder Top:" str= -> true }T
T{ $1613c zstr-decode   S" From Ladder Top to the Gas Room:" str= -> true }T
T{ $16154 zstr-decode   S" It's great for blowing up dim-witted adventurers who wander into a coal mine with an open flame." str= -> true }T
T{ $16190 zstr-decode   S" Congratulations! Getting the stiletto is rare. If you keep it away from the Thief, he won't attack you." str= -> true }T
T{ $161d0 zstr-decode   S" More General Questions" str= -> true }T
T{ $161e4 zstr-decode   S" A battery-powered brass lantern is on the trophy case." str= -> true }T
T{ $16208 zstr-decode   S" The prayer is inscribed in an ancient script, rarely used today. It seems to be a philippic against small insects, absent-mindedness, and the picking up and dropping of small objects. The final verse consigns trespassers to the land of the dead. All evidence indicates that the beliefs of the ancient Zorkers were obscure." str= -> true }T
T{ $162c4 zstr-decode   S" The path is too narrow." str= -> true }T
T{ $162d0 zstr-decode   S" Unfortunately, the magic boat doesn't provide protection from the rocks and boulders one meets at the bottom of waterfalls. Including this one." str= -> true }T
T{ $1631c zstr-decode   S" A good slash, but it misses the " str= -> true }T
T{ $16330 zstr-decode   S" A good stroke, but it's too slow; the " str= -> true }T
T{ $16348 zstr-decode   S" Take a very close look at the commandment in the black book." str= -> true }T
T{ $16370 zstr-decode   S" Take advantage of the silence in the Loud Room while the reservoir fills." str= -> true }T
T{ $1639c zstr-decode   S" Gooey gunk like this is good for patching leaks in water pipes or boats." str= -> true }T
T{ $16400 zstr-decode   S" Very good. Now you can go to the second grade." str= -> true }T
T{ $16460 zstr-decode   S" The quickness of your thrust knocks the " str= -> true }T
T{ $16474 zstr-decode   S" Speed is of the essence, too -- don't waste any more time than is necessary between steps." str= -> true }T
T{ $164bc zstr-decode   S" The rank undergrowth prevents eastward movement." str= -> true }T
T{ $164dc zstr-decode   S" The river turns a corner here making it impossible to see the Dam. The White Cliffs loom on the east bank and large rocks prevent landing on the west." str= -> true }T
T{ $1652c zstr-decode   S" The river descends here into a valley. There is a narrow beach on the west shore below the cliffs. In the distance a faint rumbling can be heard." str= -> true }T
T{ $16578 zstr-decode   S" The river is running faster here and the sound ahead appears to be that of rushing water. On the east shore is a sandy beach. A small area of beach can also be seen below the cliffs on the west shore." str= -> true }T
T{ $165e0 zstr-decode   S" F" str= -> true }T
T{ $165e4 zstr-decode   S" Kicking the " str= -> true }T
T{ $165ec zstr-decode   S" The room is full of water and cannot be entered." str= -> true }T
T{ $16600 zstr-decode   S" The rising water carries the boat over the dam, down the river, and over the falls. Tsk, tsk." str= -> true }T
T{ $16634 zstr-decode   S"  back, stunned." str= -> true }T
T{ $16640 zstr-decode   S" The Cyclops misses, but the backwash almost knocks you over." str= -> true }T
T{ $1665c zstr-decode   S" The Cyclops rushes you, but runs into the wall." str= -> true }T
T{ $16674 zstr-decode   S" The Cyclops sends you crashing to the floor, temporarily unconscious." str= -> true }T
T{ $1669c zstr-decode   S" The Cyclops breaks your neck with a massive smash." str= -> true }T
T{ $166b8 zstr-decode   S" The Cyclops almost knocks the wind out of you with a quick punch." str= -> true }T
T{ $166d8 zstr-decode   S" The Cyclops lands a punch that knocks the wind out of you." str= -> true }T
T{ $166f4 zstr-decode   S" The Cyclops grabs your " str= -> true }T
T{ $166fc zstr-decode   S" The Cyclops seems unable to decide whether to broil or stew his dinner." str= -> true }T
T{ $16724 zstr-decode   S" The Cyclops, no sportsman, dispatches his unconscious victim." str= -> true }T
T{ $1674c zstr-decode   S" The ramp is too slippery to climb." str= -> true }T
T{ $16760 zstr-decode   S" The Cellar Area" str= -> true }T
T{ $1676c zstr-decode   S" The Cyclops is scared silly of the name of his father's nemesis, ODYSSEUS (first letter of each line in commandment -- some computer screens are narrow and make this more difficult to see)." str= -> true }T
T{ $167e0 zstr-decode   S" The red button turns the lights on and off." str= -> true }T
T{ $167f8 zstr-decode   S" Raise or wave the sceptre while standing at the end of the rainbow." str= -> true }T
T{ $16824 zstr-decode   S" The Coal Mine Area" str= -> true }T
T{ $16834 zstr-decode   S" The solid-gold coffin used for the burial of Ramses II is here." str= -> true }T
T{ $1685c zstr-decode   S" The stream emerges from a spot too small for you to enter." str= -> true }T
T{ $1687c zstr-decode   S" The sound of rushing water is nearly unbearable here. On the east shore is a large landing area." str= -> true }T
T{ $168b0 zstr-decode   S"  isn't notably helpful." str= -> true }T
T{ $168c4 zstr-decode   S" The structural integrity of the rainbow is severely compromised, leaving you hanging in midair, supported only by water vapor. Bye." str= -> true }T
T{ $16914 zstr-decode   S" The stiletto flashes faster than you can follow, and blood wells from your leg." str= -> true }T
T{ $16940 zstr-decode   S" The stiletto touches your forehead, and the blood obscures your vision." str= -> true }T
T{ $16968 zstr-decode   S" The solution has something to do with the room's acoustics." str= -> true }T
T{ $16988 zstr-decode   S" Or solve the puzzle of the granite walls." str= -> true }T
T{ $169a4 zstr-decode   S" The Dam Area" str= -> true }T
T{ $169ac zstr-decode   S" The switch description should remind you of something." str= -> true }T
T{ $169d0 zstr-decode   S" How can I recharge my lamp?" str= -> true }T
T{ $169e4 zstr-decode   S" The sand in the Sandy Cave is most promising." str= -> true }T
T{ $16a00 zstr-decode   S" P = previous" str= -> true }T
T{ $16a0c zstr-decode   S" There is a silver chalice, intricately engraved, here." str= -> true }T
T{ $16a2c zstr-decode   S" There is an enormous diamond (perfectly cut) here." str= -> true }T
T{ $16a4c zstr-decode   S" There is an exquisite jade figurine here." str= -> true }T
T{ $16a64 zstr-decode   S" There is a brass lantern (battery-powered) here." str= -> true }T
T{ $16ab0 zstr-decode   S" There is a folded pile of plastic here which has a small valve attached." str= -> true }T
T{ $16ad4 zstr-decode   S" There is a red buoy here (probably a warning)." str= -> true }T
T{ $16aec zstr-decode   S" There is a suspicious-looking individual, holding a large bag, leaning against one wall. He is armed with a deadly stiletto." str= -> true }T
T{ $16b68 zstr-decode   S" There is an old trunk here, bulging with assorted jewels." str= -> true }T
T{ $16b88 zstr-decode   S" There is an object which looks like a tube of toothpaste here." str= -> true }T
T{ $16bac zstr-decode   S" There are old engravings on the walls here." str= -> true }T
T{ $16bc4 zstr-decode   S" There is a somewhat ruined egg here." str= -> true }T
T{ $16bd8 zstr-decode   S" There is a golden clockwork canary nestled in the egg. It has ruby eyes and a silver beak. Through a crystal window below its left wing you can see intricate machinery inside. It appears to have wound down." str= -> true }T
T{ $16c50 zstr-decode   S" There is a golden clockwork canary nestled in the egg. It seems to have recently had a bad experience. The mountings for its jewel-like eyes are empty, and its silver beak is crumpled. Through a cracked crystal window below its left wing you can see the remains of intricate machinery. It is not clear what result winding it would have, as the mainspring seems sprung." str= -> true }T
T{ $16d28 zstr-decode   S" There is no tree here suitable for climbing." str= -> true }T
T{ $16d40 zstr-decode   S" The troll fends you off with a menacing gesture." str= -> true }T
T{ $16d5c zstr-decode   S" Some invisible force prevents you from passing through the gate." str= -> true }T
T{ $16d80 zstr-decode   S" There is no safe landing spot here." str= -> true }T
T{ $16d94 zstr-decode   S" There is a suspicious-looking individual, holding a bag, leaning against one wall. He is armed with a vicious-looking stiletto." str= -> true }T
T{ $16de0 zstr-decode   S" There is a suspicious-looking individual lying unconscious on the ground." str= -> true }T
T{ $16e0c zstr-decode   S" There is a worthless piece of canvas here." str= -> true }T
T{ $16e24 zstr-decode   S"  is knocked out!" str= -> true }T
T{ $16e30 zstr-decode   S" The troll swings his axe, but it misses." str= -> true }T
T{ $16e44 zstr-decode   S" The troll's axe barely misses your ear." str= -> true }T
T{ $16e58 zstr-decode   S" The troll neatly removes your head." str= -> true }T
T{ $16e6c zstr-decode   S" The troll's axe stroke cleaves you from the nave to the chops." str= -> true }T
T{ $16e8c zstr-decode   S" The troll's axe removes your head." str= -> true }T
T{ $16e9c zstr-decode   S" The troll's swing almost knocks you over as you barely parry in time." str= -> true }T
T{ $16ec0 zstr-decode   S" The troll swings his axe, and it nicks your arm as you dodge." str= -> true }T
T{ $16ee0 zstr-decode   S" The troll charges, and his axe slashes you on your " str= -> true }T
T{ $16ef8 zstr-decode   S" The troll's axe swings down, gashing your shoulder." str= -> true }T
T{ $16f14 zstr-decode   S" The troll hits you with a glancing blow, and you are momentarily stunned." str= -> true }T
T{ $16f3c zstr-decode   S" The troll swings; the blade turns on your armor but crashes broadside into your head." str= -> true }T
T{ $16f6c zstr-decode   S" The troll's mighty blow drops you to your knees." str= -> true }T
T{ $16f84 zstr-decode   S" The troll swings, you parry, but the force of his blow knocks your " str= -> true }T
T{ $16fa4 zstr-decode   S" The troll hesitates, fingering his axe." str= -> true }T
T{ $16fbc zstr-decode   S" The troll scratches his head ruminatively:  Might you be magically protected, he wonders?" str= -> true }T
T{ $16ff4 zstr-decode   S" The thief stabs nonchalantly with his stiletto and misses." str= -> true }T
T{ $17014 zstr-decode   S" The thief tries to sneak past your guard, but you twist away." str= -> true }T
T{ $17034 zstr-decode   S" The thief knocks you out momentarily." str= -> true }T
T{ $17044 zstr-decode   S" The thief comes in from the side, feints, and inserts the blade into your ribs." str= -> true }T
T{ $1706c zstr-decode   S" The thief bows formally, raises his stiletto, and with a wry grin, ends the battle and your life." str= -> true }T
T{ $170a0 zstr-decode   S" The thief draws blood, raking his stiletto across your arm." str= -> true }T
T{ $170c0 zstr-decode   S" The thief slowly approaches, strikes like a snake, and leaves you wounded." str= -> true }T
T{ $170ec zstr-decode   S" The thief strikes like a snake! The resulting wound is serious." str= -> true }T
T{ $17114 zstr-decode   S" The thief stabs a deep cut in your upper arm." str= -> true }T
T{ $1712c zstr-decode   S" The thief strikes at your wrist, and suddenly your grip is slippery with blood." str= -> true }T
T{ $17158 zstr-decode   S" The thief rams the haft of his blade into your stomach, leaving you out of breath." str= -> true }T
T{ $17184 zstr-decode   S" The thief attacks, and you fall back desperately." str= -> true }T
T{ $171a0 zstr-decode   S" The thief neatly flips your " str= -> true }T
T{ $171b0 zstr-decode   S" The thief, a man of superior breeding, pauses for a moment to consider the propriety of finishing you off." str= -> true }T
T{ $171f0 zstr-decode   S" The thief amuses himself by searching your pockets." str= -> true }T
T{ $17210 zstr-decode   S" The thief entertains himself by rifling your pack." str= -> true }T
T{ $1722c zstr-decode   S" The thief, forgetting his essentially genteel upbringing, cuts your throat." str= -> true }T
T{ $1725c zstr-decode   S" The thief, a pragmatist, dispatches you as a threat to his livelihood." str= -> true }T
T{ $17288 zstr-decode   S" There is none. The game must have SOME limitations. You can't expect to walk to the nearest airport and fly to London to see the British Museum." str= -> true }T
T{ $172dc zstr-decode   S" How do I cross the mountains?" str= -> true }T
T{ $172f0 zstr-decode   S" How do I kill the songbird?" str= -> true }T
T{ $17304 zstr-decode   S" In China you might make bird's nest soup." str= -> true }T
T{ $17324 zstr-decode   S" How do I safely open the egg?" str= -> true }T
T{ $17338 zstr-decode   S" How do I fix the broken canary?" str= -> true }T
T{ $173d0 zstr-decode   S" How do I open the grating?" str= -> true }T
T{ $173e4 zstr-decode   S" How do I get off the house's roof?" str= -> true }T
T{ $173fc zstr-decode   S" How did you get up there?" str= -> true }T
T{ $1740c zstr-decode   S" How do I get the brass bauble?" str= -> true }T
T{ $17420 zstr-decode   S" How do I open the front door?" str= -> true }T
T{ $17434 zstr-decode   S" How do I get into the house?" str= -> true }T
T{ $17448 zstr-decode   S" There's a window in the back which is partly open." str= -> true }T
T{ $17468 zstr-decode   S" How do I get into the dungeons?" str= -> true }T
T{ $1747c zstr-decode   S" How do I negotiate with the Troll?" str= -> true }T
T{ $17494 zstr-decode   S" How do I get through the Maze?" str= -> true }T
T{ $174a8 zstr-decode   S" Some passages lead back to the same room." str= -> true }T
T{ $174c0 zstr-decode   S" There are 22 rooms west of the Troll Room." str= -> true }T
T{ $174d4 zstr-decode   S" How do I get past the Cyclops?" str= -> true }T
T{ $174ec zstr-decode   S" Fighting isn't always the answer." str= -> true }T
T{ $17504 zstr-decode   S" There are two solutions." str= -> true }T
T{ $17514 zstr-decode   S" How do I get the platinum bar?" str= -> true }T
T{ $17528 zstr-decode   S" There are actually two solutions." str= -> true }T
T{ $1753c zstr-decode   S" How do I kill the rock?" str= -> true }T
T{ $1757c zstr-decode   S" There are two Mirror Rooms." str= -> true }T
T{ $1758c zstr-decode   S" How do I enter Hades?" str= -> true }T
T{ $1759c zstr-decode   S" How do I get out of the Temple area?" str= -> true }T
T{ $175b4 zstr-decode   S" How do I blow up the dam?" str= -> true }T
T{ $175c8 zstr-decode   S" Can the river be crossed?" str= -> true }T
T{ $175d8 zstr-decode   S" There is no River God. Anything thrown in is lost forever." str= -> true }T
T{ $17600 zstr-decode   S" How do I control the boat?" str= -> true }T
T{ $17614 zstr-decode   S" How do I go over the falls?" str= -> true }T
T{ $17624 zstr-decode   S" How do I turn myself into an insect?" str= -> true }T
T{ $1763c zstr-decode   S" How do I get by the Smelly Room?" str= -> true }T
T{ $17654 zstr-decode   S" How do I use the machine?" str= -> true }T
T{ $17668 zstr-decode   S" How do I cross the chasm?" str= -> true }T
T{ $1767c zstr-decode   S" There's no bridge." str= -> true }T
T{ $1768c zstr-decode   S" How do I build a bridge?" str= -> true }T
T{ $176a0 zstr-decode   S" The timber might be useful." str= -> true }T
T{ $176b4 zstr-decode   S" But then again, maybe not." str= -> true }T
T{ $176c8 zstr-decode   S" How do I get out of the dungeons?" str= -> true }T
T{ $176dc zstr-decode   S" There are six exits." str= -> true }T
T{ $176e8 zstr-decode   S" How do I kill the Thief?" str= -> true }T
T{ $176fc zstr-decode   S" There is a high probability that he will take valuable objects (except the gold coffin) which you have seen. There is a much lower probability that he will take a nonvaluable object (again, only if you have seen it), and he may later decide to drop it." str= -> true }T
T{ $17790 zstr-decode   S" There are only two true granite walls." str= -> true }T
T{ $177a8 zstr-decode   S" The two granite walls are in the Temple and the Treasure Room." str= -> true }T
T{ $177cc zstr-decode   S" How do I get into the Stone Barrow?" str= -> true }T
T{ $177e4 zstr-decode   S" A painting by a neglected genius is here." str= -> true }T
T{ $17800 zstr-decode   S" Loosely attached to a wall is a small piece of paper." str= -> true }T
T{ $17820 zstr-decode   S" Type ECHO." str= -> true }T
T{ $1782c zstr-decode   S" Anything special about the mirror?" str= -> true }T
T{ $17840 zstr-decode   S" Anything in ZORK I is useful." str= -> true }T
T{ $17858 zstr-decode   S" One of the most valuable gems is made of carbon." str= -> true }T
T{ $17878 zstr-decode   S" Q = Resume story" str= -> true }T
T{ $17888 zstr-decode   S" A bottle is sitting on the table." str= -> true }T
T{ $1789c zstr-decode   S" Sitting on the pedestal is a flaming torch, made of ivory." str= -> true }T
T{ $178c4 zstr-decode   S" A nasty-looking troll, brandishing a bloody axe, blocks all passages out of the room." str= -> true }T
T{ $17944 zstr-decode   S" 's arm!" str= -> true }T
T{ $1794c zstr-decode   S"  is momentarily disoriented and can't fight back." str= -> true }T
T{ $1796c zstr-decode   S" Where do I find a machete?" str= -> true }T
T{ $17980 zstr-decode   S" Also, you must be holding the candles when you light them." str= -> true }T
T{ $179a0 zstr-decode   S" As you gain in points, you become a better match." str= -> true }T
T{ $179c0 zstr-decode   S" Where is HELLO SAILOR useful?" str= -> true }T
T{ $179dc zstr-decode   S" Where are my stolen treasures?" str= -> true }T
T{ $179f0 zstr-decode   S" Where can I use the shovel?" str= -> true }T
T{ $17a00 zstr-decode   S"  N = next" str= -> true }T
T{ $17a0c zstr-decode   S" The windows are all boarded." str= -> true }T
T{ $17a20 zstr-decode   S" Playing in this way with the " str= -> true }T
T{ $17a30 zstr-decode   S" Do you expect me to applaud?" str= -> true }T
T{ $17a44 zstr-decode   S" Waving the " str= -> true }T
T{ $17a4c zstr-decode   S" The window closes (more easily than it opened)." str= -> true }T
T{ $17a6c zstr-decode   S" up to your ankles." str= -> true }T
T{ $17a78 zstr-decode   S" up to your shin." str= -> true }T
T{ $17a84 zstr-decode   S" up to your knees." str= -> true }T
T{ $17a90 zstr-decode   S" up to your hips." str= -> true }T
T{ $17a9c zstr-decode   S" up to your waist." str= -> true }T
T{ $17aa8 zstr-decode   S" up to your chest." str= -> true }T
T{ $17ab4 zstr-decode   S" up to your neck." str= -> true }T
T{ $17ac0 zstr-decode   S" Another pathetic sputter, this time from you, heralds your drowning." str= -> true }T
T{ $17ae8 zstr-decode   S"  crashes down, knocking the " str= -> true }T
T{ $17afc zstr-decode   S" Rooms can be marked by dropping objects. (However, the Thief can be a pain.)" str= -> true }T
T{ $17b2c zstr-decode   S" Do you remember your mythology?" str= -> true }T
T{ $17b40 zstr-decode   S" I see no intelligence here." str= -> true }T
T{ $17b54 zstr-decode   S" Once you find an exit other than the chimney, the trap door will not close behind you." str= -> true }T
T{ $17b84 zstr-decode   S" In other words, fighting the fierce currents of the Frigid River. You manage to hold your own for a bit, but then you are carried over a waterfall and into some nasty rocks. Ouch!" str= -> true }T
T{ $17be8 zstr-decode   S" A quick stroke, but the " str= -> true }T
T{ $17bf8 zstr-decode   S"  is on guard." str= -> true }T
T{ $17c00 zstr-decode   S" A savage blow on the thigh! The " str= -> true }T
T{ $17c14 zstr-decode   S" A quick punch, but it was only a glancing blow." str= -> true }T
T{ $17c34 zstr-decode   S" Heedless of your weapons, the Cyclops tosses you against the rock wall of the room." str= -> true }T
T{ $17c60 zstr-decode   S" A quick thrust pinks your left arm, and blood starts to trickle down." str= -> true }T
T{ $17c8c zstr-decode   S" , but the thief twists his knife, and the " str= -> true }T
T{ $17ca0 zstr-decode   S" In other words, no." str= -> true }T
T{ $17cac zstr-decode   S" Can I eat the lunch?" str= -> true }T
T{ $17cbc zstr-decode   S" Can I open the trapdoor from below?" str= -> true }T
T{ $17cd0 zstr-decode   S" Can I get up the Cellar ramp?" str= -> true }T
T{ $17ce4 zstr-decode   S" Can I use the broken lantern?" str= -> true }T
T{ $17cf8 zstr-decode   S" Here's the alternative solution:" str= -> true }T
T{ $17d10 zstr-decode   S" Can I go down from the Dome Room?" str= -> true }T
T{ $17d24 zstr-decode   S" Can I go up from the Torch Room?" str= -> true }T
T{ $17d38 zstr-decode   S" Can I stop the leak?" str= -> true }T
T{ $17d48 zstr-decode   S" Can I get back across the river?" str= -> true }T
T{ $17d60 zstr-decode   S" Can I go through the Damp Cave crack?" str= -> true }T
T{ $17d78 zstr-decode   S" Build a cocoon?" str= -> true }T
T{ $17d84 zstr-decode   S" Can I get through the narrow passage?" str= -> true }T
T{ $17d98 zstr-decode   S" While next to a real granite wall, you can transport yourself to the location of the other by saying the name of the room." str= -> true }T
T{ $17ddc zstr-decode   S" Can I get into the Strange Passage?" str= -> true }T
T{ $17df4 zstr-decode   S" Nice view, lousy place to jump." str= -> true }T
T{ $17e0c zstr-decode   S" Hello." str= -> true }T
T{ $17e14 zstr-decode   S" Nice weather we've been having lately." str= -> true }T
T{ $17e30 zstr-decode   S" NW. S. W. D. N. N. N. E." str= -> true }T
T{ $17e48 zstr-decode   S" NW. S. W. U. D. NE." str= -> true }T
T{ $17e5c zstr-decode   S" Feed him the lunch and water." str= -> true }T
T{ $17e70 zstr-decode   S" How is the control panel operated?" str= -> true }T
T{ $17e88 zstr-decode   S" The yellow button activates the control panel at the dam. (The green bubble is now glowing.)" str= -> true }T
T{ $17ed8 zstr-decode   S" trunk of jewels - 15 - 5 - Reservoir" str= -> true }T
T{ $17ef4 zstr-decode   S" (Read only after you've finished the game.)" str= -> true }T
T{ $17f14 zstr-decode   S"  in pain." str= -> true }T
T{ $17f1c zstr-decode   S" Breaking it is not a good idea." str= -> true }T
T{ $17f30 zstr-decode   S" Discretion is the better part of valor." str= -> true }T
T{ $17f48 zstr-decode   S" Probably the easiest exit (conceptually) is by way of the grating. You will probably come across the other three exits while solving some of the harder problems, but it is not necessary to find more than one to complete the game." str= -> true }T
T{ $17fcc zstr-decode   S" Geronimo..." str= -> true }T
T{ $17fd8 zstr-decode   S" Fiddling with the " str= -> true }T
T{ $17fe4 zstr-decode   S" The Latin version of the name, ULYSSES, is also accepted." str= -> true }T
T{ $1800c zstr-decode   S" Does opening or closing the dam gates affect anything downstream?" str= -> true }T
T{ $18038 zstr-decode   S" It indicates that the control panel is activated." str= -> true }T
T{ $18058 zstr-decode   S" E. NE. SE. SW. D." str= -> true }T
T{ $1806c zstr-decode   S" The Land Beyond the Chasm" str= -> true }T
T{ $1807c zstr-decode   S" A sceptre, possibly that of ancient Egypt itself, is in the coffin. The sceptre is ornamented with colored enamel, and tapers to a sharp point." str= -> true }T
T{ $180d4 zstr-decode   S" A chasm runs southwest to northeast and the path follows it. You are on the south side of the chasm, where a crack opens into a passage." str= -> true }T
T{ $1811c zstr-decode   S" If you insist.... Poof, you're dead!" str= -> true }T
T{ $18138 zstr-decode   S" An interesting idea..." str= -> true }T
T{ $1814c zstr-decode   S"  is struck on the arm; blood begins to trickle down." str= -> true }T
T{ $18170 zstr-decode   S"  is stunned but can still fight!" str= -> true }T
T{ $18184 zstr-decode   S"  is staggered, and drops to his knees." str= -> true }T
T{ $1819c zstr-decode   S" If you had your sword when you took it, the pulse of blinding light should have served as a warning." str= -> true }T
T{ $181d8 zstr-decode   S" If you think it's useful, there's this bridge you might be interested in." str= -> true }T
T{ $18204 zstr-decode   S" The Maze" str= -> true }T
T{ $1820c zstr-decode   S" Solve the puzzle of the dam." str= -> true }T
T{ $18220 zstr-decode   S" Solve the dam problem, or figure out the mirror." str= -> true }T
T{ $18240 zstr-decode   S" If you launch the boat from Sandy Beach, you can cross the river to the west to White Cliffs South." str= -> true }T
T{ $18278 zstr-decode   S" If your lantern battery is dead, forget it." str= -> true }T
T{ $18294 zstr-decode   S" It will dig only into very soft soil." str= -> true }T
T{ $182ac zstr-decode   S" ... burned the black book?" str= -> true }T
T{ $182c0 zstr-decode   S" Conquering his fears, the troll puts you to death." str= -> true }T
T{ $182dc zstr-decode   S"  goes flying." str= -> true }T
T{ $182e8 zstr-decode   S" RETURN = see new hint" str= -> true }T
T{ $182fc zstr-decode   S" It must be undamaged, of course." str= -> true }T
T{ $18310 zstr-decode   S" SW. D. E. N. D. N. N. N. E." str= -> true }T
T{ $1832c zstr-decode   S" SW. D. E. N. E. S. SE." str= -> true }T
T{ $18344 zstr-decode   S" Old Man River" str= -> true }T
T{ $18350 zstr-decode   S" How may total points are there?" str= -> true }T
T{ $18364 zstr-decode   S" Nowhere. (You were warned.)" str= -> true }T
T{ $18378 zstr-decode   S" Clang! Crash! The " str= -> true }T
T{ $18388 zstr-decode   S"  takes a fatal blow and slumps to the floor dead." str= -> true }T
T{ $183a8 zstr-decode   S" No." str= -> true }T
T{ $183ac zstr-decode   S" ... damaged the painting?" str= -> true }T
T{ $183c0 zstr-decode   S" Try it." str= -> true }T
T{ $183c8 zstr-decode   S" Try it in the sand." str= -> true }T
T{ $183d4 zstr-decode   S" platinum bar - 10 - 5 - Loud Room" str= -> true }T
T{ $183f0 zstr-decode   S" On a table is a nasty-looking knife." str= -> true }T
T{ $18408 zstr-decode   S" It is too narrow for most insects." str= -> true }T
T{ $18418 zstr-decode   S" A pathetically babbling troll is here." str= -> true }T
T{ $18430 zstr-decode   S" Your " str= -> true }T
T{ $18434 zstr-decode   S"  jumps nimbly aside." str= -> true }T
T{ $18444 zstr-decode   S"  as your " str= -> true }T
T{ $18448 zstr-decode   S"  pinks the " str= -> true }T
T{ $18450 zstr-decode   S" Your stroke lands, but it was only the flat of the blade." str= -> true }T
T{ $18470 zstr-decode   S" It is broken beyond repair." str= -> true }T
T{ $18484 zstr-decode   S" It is also a treasure." str= -> true }T
T{ $18494 zstr-decode   S" No. The only way to keep the trapdoor from closing behind you is to find another exit (other than the chimney, which is very limited)." str= -> true }T
T{ $184dc zstr-decode   S" It is essential that you make a map of the Maze." str= -> true }T
T{ $184f8 zstr-decode   S" All ten directions are used: N, S, E, W, NE, NW, SE, SW, UP and DOWN." str= -> true }T
T{ $18534 zstr-decode   S" It is likely that you have seen the necessary equipment." str= -> true }T
T{ $18554 zstr-decode   S" It is found in the Attic." str= -> true }T
T{ $18564 zstr-decode   S" Tie the rope to the railing." str= -> true }T
T{ $18578 zstr-decode   S" It is also possible to cross the rainbow." str= -> true }T
T{ $18594 zstr-decode   S" Not bloody likely." str= -> true }T
T{ $185a4 zstr-decode   S" It is a source of carbon." str= -> true }T
T{ $185b4 zstr-decode   S" It is possible to distract him for one move by giving him something of value." str= -> true }T
T{ $185e4 zstr-decode   S" It is always best to conserve resources. You can prolong its life by turning it off whenever you can and using alternate light sources." str= -> true }T
T{ $18638 zstr-decode   S" It is a weapon, nothing more." str= -> true }T
T{ $18648 zstr-decode   S" ivory torch - 14 - 6 - Torch Room" str= -> true }T
T{ $18664 zstr-decode   S" huge diamond - 10 - 10 - you create it" str= -> true }T
T{ $187a0 zstr-decode   S" As the knife approaches its victim, your mind is submerged by an overmastering will. Slowly, your hand turns, until the rusty blade is an inch from your neck. The knife seems to sing as it savagely slits your throat." str= -> true }T
T{ $1881c zstr-decode   S" I'm afraid that the leap you attempted has done you in." str= -> true }T
T{ $1883c zstr-decode   S" I'm afraid you have done drowned yourself." str= -> true }T
T{ $18858 zstr-decode   S"  misses the " str= -> true }T
T{ $18860 zstr-decode   S" Open it and climb through." str= -> true }T
T{ $18874 zstr-decode   S" Move the rug." str= -> true }T
T{ $18880 zstr-decode   S" Type, WHAT IS A GRUE." str= -> true }T
T{ $18898 zstr-decode   S" Open the dam gates." str= -> true }T
T{ $188a8 zstr-decode   S" The Round Room Area" str= -> true }T
T{ $188b4 zstr-decode   S" 350. Any time you say QUIT, RESTART, or SCORE, this is pointed out." str= -> true }T
T{ $188ec zstr-decode   S" As the Thief wanders about stealing things, he puts them in his bag. Whenever he stops in his Treasure Room, he drops off the valuables he has collected." str= -> true }T
T{ $1894c zstr-decode   S"   " str= -> true }T
T{ $18950 zstr-decode   S" Good day." str= -> true }T
T{ $18958 zstr-decode   S" Have your eyes checked." str= -> true }T
T{ $18968 zstr-decode   S"  receives a deep gash in his side." str= -> true }T
T{ $18980 zstr-decode   S"  slips out of your hand." str= -> true }T
T{ $18990 zstr-decode   S" Have you tried saying OPEN EGG?" str= -> true }T
T{ $189ac zstr-decode   S" Have you checked all sides?" str= -> true }T
T{ $189c0 zstr-decode   S" Have you never watched an old horror movie?" str= -> true }T
T{ $189dc zstr-decode   S" To quote the black book, Oh ye who go about saying unto each: 'Hello Sailor': Dost thou know the magnitude of thy sin before the gods? ... Surely thou shalt repent of thy cunning." str= -> true }T
T{ $18a50 zstr-decode   S" gold coffin - 10 - 15 - Egypt Room" str= -> true }T
T{ $18a6c zstr-decode   S" Have you ever:" str= -> true }T
T{ $18a78 zstr-decode   S" A small leaflet is on the ground." str= -> true }T
T{ $18a8c zstr-decode   S" You are standing in front of a massive barrow of stone. In the east face is a huge stone door which is open. You cannot see into the dark of the tomb." str= -> true }T
T{ $18adc zstr-decode   S" You are facing the north side of a white house. There is no door here, and all the windows are boarded up. To the north a narrow path winds through the trees." str= -> true }T
T{ $18b28 zstr-decode   S" You are facing the south side of a white house. There is no door here, and all the windows are boarded." str= -> true }T
T{ $18b5c zstr-decode   S" You are in a small clearing in a well marked forest path that extends to the east and west." str= -> true }T
T{ $18b8c zstr-decode   S" You are on the east edge of a chasm, the bottom of which cannot be seen. A narrow passage goes north, and the path you are on continues to the east." str= -> true }T
T{ $18bd0 zstr-decode   S" You are standing on a path beside a gently flowing stream. The path follows the stream, which flows from west to east." str= -> true }T
T{ $18c10 zstr-decode   S" You are on the gently flowing stream. The upstream route is too narrow to navigate, and the downstream route is invisible due to twisting walls. There is a narrow beach to land on." str= -> true }T
T{ $18c70 zstr-decode   S" You are at the base of Flood Control Dam #3, which looms above you and to the north. The river Frigid is flowing by here. Along the river are the White Cliffs which seem to form giant walls stretching from north to south along the shores of the river as it winds its way downstream." str= -> true }T
T{ $18d04 zstr-decode   S" You are on the Frigid River in the vicinity of the Dam. The river flows quietly here. There is a landing on the west shore." str= -> true }T
T{ $18d40 zstr-decode   S" You are on a narrow strip of beach which runs along the base of the White Cliffs. There is a narrow path heading south along the Cliffs and a tight passage leading west into the cliffs themselves." str= -> true }T
T{ $18da0 zstr-decode   S" You are on a rocky, narrow strip of beach beside the Cliffs. A narrow path leads north along the shore." str= -> true }T
T{ $18dd4 zstr-decode   S" You are on the east shore of the river. The water here seems somewhat treacherous. A path travels from north to south here, the south end quickly turning around a sharp corner." str= -> true }T
T{ $18e2c zstr-decode   S" You are on a large sandy beach on the east shore of the river, which is flowing quickly by. A path runs beside the river to the south here, and a passage is partially buried in sand to the northeast." str= -> true }T
T{ $18e8c zstr-decode   S" You are on top of a rainbow (I bet you never thought you would walk on a rainbow), with a magnificent view of the Falls. The rainbow travels east-west here." str= -> true }T
T{ $18ee8 zstr-decode   S" You are on a small, rocky beach on the continuation of the Frigid River past the Falls. The beach is narrow due to the presence of the White Cliffs. The river canyon opens here and sunlight shines in from above. A rainbow crosses over the falls to the east and a narrow path continues to the southwest." str= -> true }T
T{ $18f84 zstr-decode   S" You are beneath the walls of the river canyon which may be climbable here. The lesser part of the runoff of Aragain Falls flows by below. To the north is a narrow path." str= -> true }T
T{ $18fdc zstr-decode   S" You are on a ledge about halfway up the wall of the river canyon. You can see from here that the main flow from Aragain Falls twists along a passage which it is impossible for you to enter. Below you is the canyon bottom. Above you is more cliff, which appears climbable." str= -> true }T
T{ $1905c zstr-decode   S" You are at the top of the Great Canyon on its west wall. From here there is a marvelous view of the canyon and parts of the Frigid River upstream. Across the canyon, the walls of the White Cliffs join the mighty ramparts of the Flathead Mountains to the east. Following the Canyon upstream to the north, Aragain Falls may be seen, complete with rainbow. The mighty Frigid River flows out from a great dark cavern. To the west and south can be seen an immense forest, stretching for miles around. A path leads northwest. It is possible to climb down into the canyon from here." str= -> true }T
T{ $191a0 zstr-decode   S" You are standing at the entrance of what might have been a coal mine. The shaft enters the west wall, and there is another exit on the south end of the room." str= -> true }T
T{ $191f0 zstr-decode   S" You are in a small room. Strange squeaky sounds may be heard coming from the passage at the north end. You may also escape to the east." str= -> true }T
T{ $19238 zstr-decode   S"       " str= -> true }T
T{ $1923c zstr-decode   S"         " str= -> true }T
T{ $19244 zstr-decode   S"           " str= -> true }T
T{ $1924c zstr-decode   S" You are lifted up by the rising river! You try to swim, but the currents are too strong. You come closer, closer to the awesome structure of Flood Control Dam #3. The dam beckons to you. The roar of the water nearly deafens you, but you remain conscious as you tumble over the dam toward your certain doom among the rocks at its base." str= -> true }T
T{ $1930c zstr-decode   S" You are surrounded by a wall of sand on all sides." str= -> true }T
T{ $19328 zstr-decode   S" , tastes it, and throws it to the ground in disgust." str= -> true }T
T{ $19344 zstr-decode   S" Trolls tend not to be conversational. They require a much more direct approach." str= -> true }T
T{ $19378 zstr-decode   S" Now, the alternative solution:" str= -> true }T
T{ $1938c zstr-decode   S" How silly!" str= -> true }T
T{ $19394 zstr-decode   S" Looking into it can be fun." str= -> true }T
T{ $193a4 zstr-decode   S" The Thief is a cunning and dangerous opponent, skilled in the martial arts. Novice Zorkers would do well to avoid him." str= -> true }T
T{ $193f0 zstr-decode   S" The Thief, of course." str= -> true }T
T{ $19400 zstr-decode   S" The Thief is constantly moving about." str= -> true }T
T{ $19418 zstr-decode   S" The Treasure Room is guarded by the Cyclops." str= -> true }T
T{ $19434 zstr-decode   S" The Thief." str= -> true }T
T{ $1943c zstr-decode   S" Egyptian sceptre - 4 - 6 - in the coffin" str= -> true }T
T{ $19458 zstr-decode   S" Shifting in the midst of a thrust, the thief knocks you temporarily unconscious with the haft of his stiletto." str= -> true }T
T{ $19494 zstr-decode   S" You become a spirit if you have visited a certain location before death." str= -> true }T
T{ $194bc zstr-decode   S" large emerald - 5 - 10 - in the buoy" str= -> true }T
T{ $194d4 zstr-decode   S" You cannot climb any higher." str= -> true }T
T{ $194e4 zstr-decode   S" You cannot go down without fracturing many bones." str= -> true }T
T{ $19500 zstr-decode   S" You cannot reach the rope." str= -> true }T
T{ $1950c zstr-decode   S" You cannot go upstream due to strong currents." str= -> true }T
T{ $19528 zstr-decode   S" You can land either to the east or the west." str= -> true }T
T{ $19540 zstr-decode   S" You cannot fit through this passage with that load." str= -> true }T
T{ $19550 zstr-decode   S" You can't swim in the dungeon." str= -> true }T
T{ $19560 zstr-decode   S" You can't be serious." str= -> true }T
T{ $1956c zstr-decode   S" high in your lungs." str= -> true }T
T{ $19578 zstr-decode   S" You charge, but the " str= -> true }T
T{ $19584 zstr-decode   S" You can't be afraid to try anything in ZORK I (but it may make sense to SAVE your state first)." str= -> true }T
T{ $195c0 zstr-decode   S" No. You won't ever get up the ramp." str= -> true }T
T{ $19614 zstr-decode   S" You can turn the bolt." str= -> true }T
T{ $19620 zstr-decode   S" You can say BOARD (or GET IN), DISEMBARK (or GET OUT), LAUNCH, and LAND (or a direction towards a landing area). You can also let the current carry you." str= -> true }T
T{ $1969c zstr-decode   S" You can cross it and get the pot of gold." str= -> true }T
T{ $196b4 zstr-decode   S" You can't." str= -> true }T
T{ $196bc zstr-decode   S" You can make a diamond out of coal." str= -> true }T
T{ $196d0 zstr-decode   S" You can almost always avoid a confrontation by walking away. Although you may be robbed, at least you won't be killed." str= -> true }T
T{ $19714 zstr-decode   S" You can get the contents of the bag by defeating him in a fight." str= -> true }T
T{ $1973c zstr-decode   S" Above the trophy case hangs an elvish sword of great antiquity." str= -> true }T
T{ $19768 zstr-decode   S" The White Cliffs prevent your landing here." str= -> true }T
T{ $19784 zstr-decode   S"  it at the time." str= -> true }T
T{ $19790 zstr-decode   S" You dodge as the thief comes in low." str= -> true }T
T{ $197a4 zstr-decode   S" You don't." str= -> true }T
T{ $197ac zstr-decode   S" Above Ground" str= -> true }T
T{ $197b8 zstr-decode   S" He's hungry, isn't he?" str= -> true }T
T{ $197cc zstr-decode   S" Try praying." str= -> true }T
T{ $19814 zstr-decode   S" Try putting something inside and turning the machine on with the screwdriver. Have a dictionary handy." str= -> true }T
T{ $19854 zstr-decode   S" Try praying at the altar." str= -> true }T
T{ $19868 zstr-decode   S" ... lit the candles with the torch?" str= -> true }T
T{ $19878 zstr-decode   S" It appears that that last blow was too much for you. I'm afraid you are dead." str= -> true }T
T{ $198a0 zstr-decode   S" Lying in one corner of the room is a beautifully carved crystal skull. It appears to be grinning at you rather nastily." str= -> true }T
T{ $198e4 zstr-decode   S" Lying half buried in the mud is an old trunk, bulging with jewels." str= -> true }T
T{ $1990c zstr-decode   S"  doesn't seem to work." str= -> true }T
T{ $19918 zstr-decode   S" W. W. W. U. SW. U. D. NE." str= -> true }T
T{ $19930 zstr-decode   S" W. W. W. U. SW. E. S. SE." str= -> true }T
T{ $19948 zstr-decode   S" silver chalice - 10 - 5 - Treasure Room" str= -> true }T
T{ $19968 zstr-decode   S" For Your Amusement" str= -> true }T
T{ $19974 zstr-decode   S" In the trophy case is an ancient parchment which appears to be a map." str= -> true }T
T{ $1999c zstr-decode   S" In the bird's nest is a large egg encrusted with precious jewels, apparently scavenged by a childless songbird. The egg is covered with fine gold inlay, and ornamented in lapis lazuli and mother-of-pearl. Unlike most eggs, this one is hinged and closed with a delicate looking clasp. The egg appears extremely fragile." str= -> true }T
T{ $19a54 zstr-decode   S" In the movies, your life would be passing before your eyes." str= -> true }T
T{ $19a74 zstr-decode   S"  dodges." str= -> true }T
T{ $19a7c zstr-decode   S" ." str= -> true }T
T{ $19a80 zstr-decode   S" A glancing blow from the Cyclops' fist." str= -> true }T
T{ $19a9c zstr-decode   S" You get 10 points for getting into the house, 25 for getting into the Cellar, 5 for getting past the Troll, 13 for getting to the Drafty Room, and 25 for getting to the Treasure Room." str= -> true }T
T{ $19b08 zstr-decode   S" ... opened the grating from beneath while the leaves were still on it?" str= -> true }T

S" All passed" type cr bye
